[project]
authors = ["Silvio <silvio.traversaro@iit.it>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "teststagingupload"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
requests = ">=2.32.3,<3"
anaconda-client = ">=1.12.3,<2"
